volumes:
  homeassistant_config:

networks:
  default_network:
    external: true

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - "8123:8123"
    volumes:
      - homeassistant_config:/config
      - ./certificates:/ssl
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    networks:
      default_network:
        ipv4_address: 10.0.0.16
    privileged: true
