version: '2'

services:
  db:
    container_name: nextcloud-db
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /data/nextcloud/db_data:/var/lib/mysql
    networks:
      - nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    container_name: nextcloud-redis-cache
    networks:
      - nextcloud
    restart: unless-stopped

  app:
    container_name: nextcloud-app
    image: nextcloud
    restart: unless-stopped
    ports:
      - "10080:80"
    volumes:
      - /data/nextcloud/nextcloud_data:/var/www/html
    networks:
      - nextcloud
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
networks:
  nextcloud:
    external: true
