networks:
  proxy:
    external: true

volumes:
  nextcloud-data:
  db-data:

services:

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - proxy
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-redis:
    container_name: nextcloud-redis-cache
    image: redis:alpine
    restart: unless-stopped
    networks:
      - proxy

  nextcloud-app:
    container_name: nextcloud-app
    image: nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html
    networks:
      - proxy
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST
    depends_on:
      - nextcloud-db
      - nextcloud-redis

  nextcloud-cron:
    container_name: nextcloud-cron
    image: nextcloud:stable-fpm
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html
    entrypoint: /cron.sh
    networks:
      - proxy
    depends_on:
      - nextcloud-db
      - nextcloud-redis
