services:

  db:
    container_name: nextcloud-db
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - /data/nextcloud/db_data:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    container_name: nextcloud-redis-cache
    image: redis:alpine
    restart: unless-stopped
    networks:
      - nextcloud

  nextcloud:
    container_name: nextcloud-app
    image: nextcloud
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - /data/nextcloud/nextcloud_data:/var/www/html
    networks:
      - nextcloud
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  cron:
    container_name: nextcloud-cron
    image: nextcloud:stable-fpm
    restart: unless-stopped
    volumes:
      - /data/nextcloud/nextcloud_data:/var/www/html
    entrypoint: /cron.sh
    networks:
      - nextcloud
    depends_on:
      - db
      - redis

networks:
  nextcloud:
    external: true
