networks:
  default_network:
    external: true

volumes:
  nextcloud_data:
  db_data:

services:

  nextcloud_db:
    container_name: nextcloud_db
    env_file:
      - .env
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - default_network

  nextcloud_redis:
    container_name: nextcloud_redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - default_network

  nextcloud_app:
    container_name: nextcloud_app
    env_file:
      - .env
    image: nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      default_network:
        ipv4_address: 10.0.0.8
    environment:
      - OVERWRITEHOST=${OVERWRITEHOST}
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://${OVERWRITEHOST}" ]
      interval: 30s
      timeout: 10s
      retries: 3


  nextcloud_cron:
    container_name: nextcloud_cron
    image: nextcloud:stable-fpm
    restart: unless-stopped
    volumes:
      - nextcloud_data:/var/www/html
    entrypoint: /cron.sh
    networks:
      - default_network
    depends_on:
      - nextcloud_db
      - nextcloud_redis
