networks:
  proxy:
    external: true

volumes:
  nginx-data:
  letsencrypt-data:

services:

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - nginx-data:/data
      - letsencrypt-data:/etc/letsencrypt
    networks:
      - proxy
