networks:
  proxy:
    external: true

volumes:
  nginx-data:
  letsencrypt-data:
    external: true
    name: letsencrypt-data

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx-data:/data
      - letsencrypt-data:/etc/letsencrypt
    networks:
      - proxy
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://npm.stereov.com" ]
      interval: 30s
      timeout: 10s
      retries: 3
