volumes:
  mail_data:
  mail_state:
  mail_logs:
  dms_config:
  letsencrypt_data:
    external: true
    name: letsencrypt_data
  roundcube_data:

networks:
  default_network: 
    external: true

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    domainname: ${DOMAIN_NAME}
    hostname: ${DOMAIN_NAME}
    env_file:
      - mailserver.env
      - .env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - mail_data:/var/mail/
      - mail_state:/var/mail-state/
      - mail_logs:/var/log/mail/
      - dms_config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - letsencrypt_data:/etc/letsencrypt:ro
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: unless-stopped
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  roundcube:
    image: roundcube/roundcubemail
    container_name: roundcube
    volumes:
      - roundcube_data:/var/roundcube/db
    restart: unless-stopped
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://${DOMAIN_NAME}
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://${DOMAIN_NAME}
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBE_DOMAIN=${ROUNDCUBE_DOMAIN}
    networks:
      default_network:
        ipv4_address: 10.0.0.15
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://${ROUNDCUBE_DOMAIN}" ]
      interval: 30s
      timeout: 10s
      retries: 3
