networks:
  proxy:
    external: true

volumes:
  npm-data:
  letsencrypt-data:
    external: true
    name: letsencrypt-data

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    environment:
      - NPM_DOMAIN=${NPM_DOMAIN}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - npm-data:/data
      - letsencrypt-data:/etc/letsencrypt
    networks:
      - proxy
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://${NPM_DOMAIN}" ]
      interval: 30s
      timeout: 10s
      retries: 3
