networks:
  default_network:
    external: true

volumes:
  npm_data:
  letsencrypt_data:
    external: true
    name: letsencrypt_data

services:
  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - npm_data:/data
      - letsencrypt_data:/etc/letsencrypt
    networks:
      default_network:
        ipv4_address: 10.0.0.5
      
